services:
  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: blackjack_mysql
    # ESTA ES LA LÍNEA NUEVA MÁGICA:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackjack_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Servicio de MongoDB
  mongo:
    image: mongo:latest
    container_name: blackjack_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Tu Aplicación (API)
  app:
    image: blackjack-api:latest
    container_name: blackjack_app
    build: .
    ports:
      - "8082:8081"
    depends_on:
      - mysql
      - mongo
    environment:
      # Sobrescribimos la configuración de conexión para que apunte a los contenedores
      # en lugar de a 'localhost'
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/blackjack_db
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/blackjack_db
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root

volumes:
  mysql_data:
  mongo_data: